In [2]:
# 2. Importar las librerías necesarias:
import numpy as np
import pandas as pd

In [3]:
# 3. Cargar los datos (lectura y procesamiento de datos - Pandas):
# Limpia los datos eliminando filas con valores nulos utilizando el método dropna(). Esto te permitirá trabajar solo con datos válidos.

# SALES
df_sales = pd.read_csv('1756803113331-sales.csv')
df_sales.dropna()
print(df_sales.head())

# INVENTORIES
df_inventories = pd.read_csv('1756803222042-inventories.csv')
df_inventories.dropna()
print(df_inventories.head())

# SATISFACTION
df_satisfaction = pd.read_csv('1756803304185-satisfaction.csv')
df_satisfaction.dropna()
print(df_satisfaction.head())

# MERGE SALES + INVENTORIES
df_sales_inventories = pd.merge(df_sales, df_inventories, on=['ID_Tienda', 'Producto'])
df_sales_inventories.head()

   ID_Tienda    Producto  Cantidad_Vendida  Precio_Unitario Fecha_Venta
0          1  Producto A                20              100  2023-01-05
1          1  Producto B                15              200  2023-01-06
2          2  Producto A                30              100  2023-01-07
3          2  Producto C                25              300  2023-01-08
4          3  Producto A                10              100  2023-01-09
   ID_Tienda    Producto  Stock_Disponible Fecha_Actualización
0          1  Producto A                50          2023-01-05
1          1  Producto B                40          2023-01-06
2          2  Producto A                60          2023-01-07
3          2  Producto C                45          2023-01-08
4          3  Producto A                30          2023-01-09
   ID_Tienda  Satisfacción_Promedio Fecha_Evaluación
0          1                     85       2023-01-15
1          2                     90       2023-01-15
2          3                     70       2023-01-15
3          4                     65       2023-01-15
4          5                     55       2023-01-15

,ID_Tienda,Producto,Cantidad_Vendida,Precio_Unitario,Fecha_Venta,Stock_Disponible,Fecha_Actualización
0,1,Producto A,20,100,2023-01-05,50,2023-01-05
1,1,Producto B,15,200,2023-01-06,40,2023-01-06
2,2,Producto A,30,100,2023-01-07,60,2023-01-07
3,2,Producto C,25,300,2023-01-08,45,2023-01-08
4,3,Producto A,10,100,2023-01-09,30,2023-01-09

In [33]:
# ----------------------------------
#  4. Exploración de datos (Pandas)
# ----------------------------------

# 4.1.1 Calcula las CANTIDADES VENDIDAS TOTALES por PRODUCTO.
cantidades_totales_producto = df_sales_inventories.groupby('Producto')['Cantidad_Vendida'].sum()
#print(f"Las CANTIDADES VENDIDAS TOTALES por PRODUCTO son {cantidades_totales_producto}")

# 4.1.2 Calcula las CANTIDADES VENDIDAS TOTALES por TIENDA.
cantidades_totales_tienda = df_sales_inventories.groupby('ID_Tienda')['Cantidad_Vendida'].sum()
#print(f"Las CANTIDADES VENDIDAS TOTALES por TIENDA son {cantidades_totales_tienda}")

# 4.2 Calcula los INGRESOS TOTALES por TIENDA: multiplicando la CANTIDAD VENDIDA por el PRECIO.
df_sales_inventories['Ingresos_Totales_Tienda'] = df_sales_inventories['Cantidad_Vendida'] * df_sales_inventories['Precio_Unitario']
#df_sales_inventories.head()
print(f"Los INGRESOS TOTALES por TIENDA son: {df_sales_inventories.groupby('ID_Tienda')['Ingresos_Totales_Tienda'].sum()}")

# 4.3 Genera un resumen estadístico de las VENTAS utilizando el método describe() para obtener la media, mediana y otras métricas clave.
resumen_estadistico = df_sales_inventories['Cantidad_Vendida'].describe()
print(resumen_estadistico)

# 4.4 Si los PRODUCTOS están clasificados por CATEGORÍAS: calcula el promedio de VENTAS por TIENDA y CATEGORÍA de productos
# NO VEO QUE ESTÉN CATEGORIZADOS POR CATEGORÍAS

Los INGRESOS TOTALES por TIENDA son: ID_Tienda
1     5000
2    10500
3     9000
4    13000
5    13000
Name: Ingresos_Totales_Tienda, dtype: int64
count    10.000000
mean     25.000000
std       9.128709
min      10.000000
25%      20.000000
50%      25.000000
75%      30.000000
max      40.000000
Name: Cantidad_Vendida, dtype: float64

In [32]:
# ----------------------------------
# 5. Análisis de inventarios (Pandas)
# ----------------------------------

# 5.1 Calcula la ROTACIÓN de INVENTARIOS para cada TIENDA: dividiendo las VENTAS TOTALES por el STOCK disponible de cada producto.
df_sales_inventories['Rotacion'] = df_sales_inventories['Cantidad_Vendida'] / df_sales_inventories['Stock_Disponible'] * 100
df_sales_inventories.head()

# 5.2 Almacena los resultados en una nueva columna dentro del DataFrame de inventarios.
# HECHO

#5.3 Filtra y muestra las tiendas con niveles críticos de inventario:
# aquellas tiendas donde el porcentaje de productos vendidos sea menor al 10% del stock disponible.
tiendas_criticas = df_sales_inventories[df_sales_inventories['Rotacion'] < 10]
print(tiendas_criticas)

Empty DataFrame
Columns: [ID_Tienda, Producto, Cantidad_Vendida, Precio_Unitario, Fecha_Venta, Stock_Disponible, Fecha_Actualización, Ingresos_Totales_Tienda, Rotacion]
Index: []

In [37]:
# 6. Satisfacción del cliente (Pandas)

# 6.1 Realiza un análisis de la satisfacción de los clientes en cada tienda. Relaciona estos datos con el rendimiento de las ventas.
df_sales_inventories_satisfaction = pd.merge(df_sales_inventories, df_satisfaction, on=['ID_Tienda'])
df_sales_inventories_satisfaction.groupby('ID_Tienda')[['ID_Tienda', 'Rotacion']].sum()

# 6.2 Filtra las tiendas con niveles bajos de satisfacción (< 60%)
df_sales_inventories_satisfaction[df_sales_inventories_satisfaction['Satisfacción_Promedio'] < 60]

,ID_Tienda,Producto,Cantidad_Vendida,Precio_Unitario,Fecha_Venta,Stock_Disponible,Fecha_Actualización,Ingresos_Totales_Tienda,Rotacion,Satisfacción_Promedio,Fecha_Evaluación
8,5,Producto B,20,200,2023-01-13,40,2023-01-13,4000,50.0,55,2023-01-15
9,5,Producto C,30,300,2023-01-14,60,2023-01-14,9000,50.0,55,2023-01-15